---
- hosts: websever
  become: yes
  vars:
    build_number: '{{ BUILD_NUMBER }}'
  tasks:
      
    - name: login to jfrog
      shell: docker login -u kavitha -p Kavitha31 artifact31.jfrog.io    
    
    - name: pull an image
      shell: docker pull artifact31.jfrog.io/test-docker-local/war_on_container:v{{ BUILD_NUMBER }}

    #- name: remove container
     # shell: docker rm -f devopsAppDeploy
        
    - name: create a application container
      shell: docker run -id --name devopsAppDeploy -p 8111:8080 artifact31.jfrog.io/test-docker-local/war_on_container:v{{ BUILD_NUMBER }}
   
