---
- hosts: websever
  become: yes
  vars:
    build_number: '{{ BUILD_NUMBER }}'
  tasks:
      
    - name: login to jfrog
      shell: docker login -u gadhar.kavitha@gmail.com -p Kavitha31 artifact31.jfrog.io    
    
    - name: pull an image
      shell: docker pull artifact31.jfrog.io/docker-demo/war_on_container:v{{ BUILD_NUMBER }}

    #- name: remove container
     # shell: docker rm -f devopsAppDeploy
        
    - name: create a application container
      shell: docker run -id --name devopsAppDeploy{{ BUILD_NUMBER }} -p 8111:8080 artifact31.jfrog.io/docker-demo/war_on_container:v{{ BUILD_NUMBER }}
   
